apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w12o78s5x-go
  janus-idp.io/tekton: w12o78s5x-go
  backstage.io/kubernetes-id: w12o78s5x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w12o78s5x-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
