apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: w12o78s5x-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: w12o78s5x-go 
  name: w12o78s5x-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: w12o78s5x-go 
